# Generated by Django 4.1.2 on 2022-11-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mldata_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mldata',
            name='name',
        ),
        migrations.AddField(
            model_name='mldata',
            name='capital_gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='capital_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='education',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='education_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='fnlwgt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='hoursperweek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='martial_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='native_country',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='occupation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='race',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='relationship',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='sex',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mldata',
            name='workclass',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mldata',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
